# Generated by Django 6.0.5 on 2026-07-05 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_section_messagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='adopted_groups',
            field=models.ManyToManyField(blank=True, related_name='adopted_by', to='contacts.contactgroup'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='is_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_contact_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
