# Generated by Django 6.0.5 on 2026-09-03 10:00

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True, validators=[contacts.models.validate_mobile_number]),
        ),
    ]
