# Generated by Django 6.0.5 on 2026-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('INSTRUCTOR', 'Instructor'), ('SUBSCRIBER', 'Subscriber')], default='SUBSCRIBER', max_length=20),
        ),
    ]
