# Generated by Django 6.0.5 on 2026-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ite_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user can login to the ITE admin dashboard.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ite_instructor',
            field=models.BooleanField(default=False, help_text='Designates whether this instructor belongs to the ITE department.'),
        ),
    ]
