"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_2ye7gv#*#$44pq9id67dt*s2b*awt$5j$*lw9&o=el2ubli6q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "rest_framework",

    "users",
    "subscribers",
    "plans",
    "gateway",
    "contacts",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = "users.User"

CELERY_BROKER_URL = "redis://localhost:6379"

CELERY_RESULT_BACKEND = "redis://localhost:6379"

CELERY_ACCEPT_CONTENT = [
    "json"
]

CELERY_TASK_SERIALIZER = "json"

# Reliability: don't ack a task until it actually finishes. If a worker
# process dies mid-send (crash, power loss on the Windows box, etc),
# Redis redelivers the task to another worker instead of silently
# losing it.
CELERY_TASK_ACKS_LATE = True

# Paired with acks_late: don't let one worker thread hoard a big batch
# of queued messages while the other modem's thread sits idle. Keeps
# work spread evenly across the two modem threads.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# --- Broker visibility timeout ---------------------------------------
#
# Bug fix: previously this had no override, so with
# CELERY_TASK_ACKS_LATE=True, Celery's Redis transport fell back to its
# default visibility_timeout of 3600 seconds (1 hour). If a task is
# ever lost without being acked (worker killed, process crashed,
# machine slept), Redis won't consider that message safe to redeliver
# to another worker until that hour elapses — which lines up exactly
# with messages being reported stuck at PENDING "for over an hour".
#
# This setting is a broker/Kombu-level concern, independent of which
# execution pool the worker runs — unlike CELERY_TASK_TIME_LIMIT below,
# it's not something Celery quietly ignores under --pool=threads, so
# it's a real, working part of the fix.
#
# NOTE: this project deliberately does NOT set CELERY_TASK_TIME_LIMIT /
# CELERY_TASK_SOFT_TIME_LIMIT. Those are enforced by celery.concurrency.
# prefork's AsynPool (real per-process soft/hard timers) — but this
# worker runs `--pool=threads` (prefork needs os.fork(), unavailable on
# Windows), and celery.concurrency.thread.TaskPool has no timeout
# machinery whatsoever, on any OS: it's a bare ThreadPoolExecutor.submit()
# with signal_safe=False. Setting those two options here would silently
# do nothing but look like a safety net that doesn't exist. The actual
# hard-timeout enforcement for a wedged modem call lives in
# gateway/modem_subprocess.py instead, which can forcibly kill a stuck
# operation because it's a real OS process, not a thread.

CELERY_BROKER_TRANSPORT_OPTIONS = {
    # Comfortably above MODEM_SEND_HARD_TIMEOUT_SECONDS (see tasks.py)
    # so a task that's still legitimately running is never redelivered
    # as a duplicate, but nowhere near the 1-hour default — a truly
    # lost task now comes back in minutes, not an hour.
    "visibility_timeout": 600,
}

# Run the worker with: celery -A core worker --pool=threads --concurrency=2 -l info
# --pool=threads (not the default prefork pool) because prefork relies on
# os.fork(), which isn't available on Windows. --concurrency=2 matches
# the two SIM800 modems so both can be sending at the same time; bump
# this if a third modem is ever added.

SMS_MODEM_PORT = "COM3"
SMS_MODEM_PORTS = [
    "COM3",
    "COM4",
]
SMS_MODEM_BAUDRATE = 115200

SMS_DEV_MODE = False

# Hard wall-clock cap on a single send attempt (across however many
# candidate modems Sim800Service.send_sms tries internally), enforced
# via a killable child process — see gateway/modem_subprocess.py for
# why this can't just be a Celery task time limit on this worker pool.
# Sizing: a send can legitimately spend up to
# RECIPIENT_LOCK_WAIT_TIMEOUT_SECONDS=40s (tasks.py) waiting its turn,
# then per candidate port up to PORT_LOCK_ACQUIRE_TIMEOUT=15s +
# several AT commands (~10s timeout each) + RESPONSE_TIMEOUT=30s
# (services.py). 240s comfortably covers that worst case across both
# configured modems with margin.
SMS_SEND_HARD_TIMEOUT_SECONDS = 240