# Generated by Django 6.0.5 on 2026-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_apikey_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='response_message',
            field=models.TextField(blank=True),
        ),
    ]
