# Generated by Django 6.0.5 on 2026-06-27 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_smslog_response_message'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber'),
        ),
    ]
