# Generated by Django 6.0.5 on 2026-08-21 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_smslog_sent_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='How many send attempts have been made so far, including the current one.'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='modem_port',
            field=models.CharField(blank=True, help_text='The modem/COM port the most recent attempt was dispatched to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RETRYING', 'RETRYING'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SmsRetryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Number of retry attempts after the first failed send, before marking FAILED.')),
                ('base_backoff_seconds', models.PositiveIntegerField(default=30, help_text='Delay before the first retry, in seconds.')),
                ('backoff_multiplier', models.FloatField(default=2.0, help_text='Each subsequent retry waits base_backoff_seconds * (multiplier ^ attempt_number).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]