# Generated by Django 6.0.5 on 2026-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_smslog_attempts_smslog_modem_port_and_more'),
        ('plans', '0002_plan_message_limit_plan_plan_type'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('subscriber',), name='one_active_subscription_per_subscriber'),
        ),
    ]