# Generated by Django 6.0.5 on 2026-08-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_smslog_retry_count'),
        ('gateway', '0007_subscription_one_active_subscription_per_subscriber'),
    ]

    operations = [
    ]
