# Generated by Django 6.0.5 on 2026-08-30 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_merge_20260823_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='messages_sent_this_period',
            field=models.PositiveIntegerField(default=0, help_text="Successful sends counted against the plan's message_limit, for the current period only."),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_start',
            field=models.DateField(default=datetime.date.today, help_text='Start of the current usage period. Rolls forward automatically once PERIOD_LENGTH_DAYS elapses.'),
        ),
    ]
