# Generated by Django 6.0.5 on 2026-08-31 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_subscription_messages_sent_this_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=20, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('signal_csq', models.PositiveIntegerField(blank=True, help_text='Raw AT+CSQ value (0-31). Null if unknown/unreadable.', null=True)),
                ('signal_bucket', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('WEAK', 'WEAK'), ('GOOD', 'GOOD'), ('EXCELLENT', 'EXCELLENT')], default='UNKNOWN', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('last_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
