# Generated by Django 6.0.5 on 2026-09-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0010_modemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='modemstatus',
            name='registration_detail',
            field=models.TextField(blank=True, help_text='Human-readable explanation of registration_state for the admin UI.'),
        ),
        migrations.AddField(
            model_name='modemstatus',
            name='registration_state',
            field=models.CharField(choices=[('REGISTERED_HOME', 'REGISTERED_HOME'), ('REGISTERED_ROAMING', 'REGISTERED_ROAMING'), ('SEARCHING', 'SEARCHING'), ('DENIED', 'DENIED'), ('NOT_SEARCHING', 'NOT_SEARCHING'), ('UNKNOWN', 'UNKNOWN'), ('NO_RESPONSE', 'NO_RESPONSE')], default='NO_RESPONSE', help_text='Raw AT+CREG? status, decoded — explains *why* is_online is what it is.', max_length=20),
        ),
        migrations.AddField(
            model_name='smslog',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('MODEM_OFFLINE', 'Modem offline / not registered'), ('WEAK_OR_NO_SIGNAL', 'Weak or no signal'), ('SIM_ERROR', 'SIM card problem'), ('BALANCE_OR_BARRED', 'Likely no credit / barred'), ('NETWORK_REJECTED', 'Rejected by network'), ('MESSAGE_REJECTED', 'Message rejected (format/content)'), ('STORAGE_FULL', 'Modem/SIM storage full'), ('TIMEOUT', 'No response in time'), ('RECIPIENT_BUSY', 'Recipient already being sent to'), ('UNKNOWN', 'Unknown / unclassified')], help_text="Coarse reason this attempt failed (modem offline, weak signal, likely no credit, etc), derived from the modem's own error code where one was available. Blank while PENDING/SENT, or if a send failed before any modem response could be classified.", max_length=30),
        ),
    ]
