# Generated by Django 6.0.5 on 2026-09-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0011_modemstatus_registration_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsretrypolicy',
            name='backoff_multiplier',
            field=models.FloatField(default=2.0, help_text='Unused now that retries are manual — kept for backward compatibility with existing rows/serializers.'),
        ),
        migrations.AlterField(
            model_name='smsretrypolicy',
            name='base_backoff_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Unused now that retries are manual — kept for backward compatibility with existing rows/serializers.'),
        ),
        migrations.AlterField(
            model_name='smsretrypolicy',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Number of manual retry attempts allowed after the first failed send, before the Retry button stops working for that message.'),
        ),
    ]
