# Generated by Django 6.0.5 on 2026-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='message_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Messages allowed per billing period for LIMITED plans (resets each period once usage enforcement is wired up). Ignored for UNLIMITED plans.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('UNLIMITED', 'UNLIMITED'), ('LIMITED', 'LIMITED')], default='UNLIMITED', max_length=20),
        ),
    ]